spring.application.name=pet-care-backend
spring.datasource.url=jdbc:mysql://localhost:3306/petcare_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2004
spring.jpa.hibernate.ddl-auto=update